name: 'spark website workflow'

on:
  push:
    branches:
      generate-register-page

strategy:
  matrix:
    node-version: 20.5.1

jobs:
  frontend_jobs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: node version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Go to frontend folder
        run: cd frontend
      - name: install dependencies
        run: npm ci
      - name: build the app
        run: npm run build --if-present
      - name: test the app
        run: npm run test
    
