name: 'spark website workflow'

on:
  push:
    branches:
      generate-register-page

jobs:
  frontend_jobs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Go to frontend folder
        run: cd frontend
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: install dependencies
        run: npm ci
      - name: build the app
        run: npm run build --if-present
      - name: test the app
        run: npm run test
        shell: bash
    
